CREATE TABLE MOTOS_LOCALIZADAS (
    OBJECT_ID NUMBER PRIMARY KEY,
    TIMESTAMP_REG DATE,
    CLASSE VARCHAR2(50),
    POS_X NUMBER,
    POS_Y NUMBER,
    X1 NUMBER,
    Y1 NUMBER,
    X2 NUMBER,
    Y2 NUMBER
);